[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
author = "Ciencia de Datos • GECI"
author-email = "ciencia.datos@islas.org.mx"
classifiers = [ "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",]
description-file = "README.md"
home-page = "https://github.com/IslasGECI/gatos"
module = "gatos"
requires = [
        "Click",
        "eradication-data-requirements==0.1.*",
        "geci-plots==0.4.*",
        "matplotlib",
        "metadatatools @ git+https://git@github.com/IslasGECI/metadata_tools@v0.2.2",
        "numpy",
        "pandas",
        "pymc3==3.11.*"
    ]
requires-python=">=3.10"

[tool.flit.scripts]
crea_tabla_pvalor = "gatos.tabla_p_valor_erradicacion_gatos:cli"
crea_tamagno_poblacion_gatos = "gatos.generaTamanioPoblacionGatos:cli"
gatos = "gatos.gatos_cli:app"
