#!/usr/bin/env python
#
# serieDeTiempoCapturasPorAnioGatosSocorro lee datos en CSV y genera serie de tiempo de captura por unidad de esfuerzo por año.
import os
import sys

import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
import numpy as np

nombre_archivo_entrada = sys.argv[1]
posiciones_barras = np.linspace(1,17,9)
tamano_fuente = 15

datos_gatos_socorro = pd.read_csv(f'{nombre_archivo_entrada}')
valores_anios = ["2011", "2012","2013", "2014","2015", "2016","2017", "2018","2019"]

esfuerzo_acumulado_anual=[]
gatos_erradicados=[]
CPUE=[] 
for i in valores_anios:
    mask = datos_gatos_socorro['fecha'].str.contains(i)
    esfuerzo_acumulado_anual.append(np.sum( datos_gatos_socorro['esfuerzo'].values[mask]))
    gatos_erradicados.append(np.sum( datos_gatos_socorro['capturas'].values[mask]))
    CPUE.append(np.sum( datos_gatos_socorro['capturas'].values[mask])/np.sum( datos_gatos_socorro['esfuerzo'].values[mask]))

fig, ax= plt.subplots(figsize=(11, 8))
plt.plot(posiciones_barras,CPUE,'-o')
plt.xticks(posiciones_barras, valores_anios)
ax.set_ylabel('Catch Per Unit Effort (CPUE)',fontsize=tamano_fuente)
ax.set_xlim(6.95, 17.03)
ax.set_ylim(0, 0.014)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
nombre_imagen_salida="reports/figures/timeSerieCPUEanual.png"
plt.savefig(f"{nombre_imagen_salida}", dpi=300)
